// SPDX-License-Identifier: MIT
#ifndef SELINOS_TCB_RESUME_M2_PROTOCOL_H
#define SELINOS_TCB_RESUME_M2_PROTOCOL_H

#include <sel4/sel4.h>

/* Phase 33: receive one preprovisioned child TCB cap and resume it exactly once. */
#define SELINOS_TCB_RESUME_M2_REQUEST 0x54524d3252455154ull /* "TRM2REQT" */
#define SELINOS_TCB_RESUME_M2_GRANTED 0x54524d3247524e54ull /* "TRM2GRNT" */
#define SELINOS_TCB_RESUME_M2_CHILD_RAN 0x54524d3243484c44ull /* "TRM2CHLD" */
#define SELINOS_TCB_RESUME_M2_SLOT 1u
#define SELINOS_TCB_RESUME_M2_GENERATION 1u

#define SELINOS_TCB_RESUME_M2_REQUEST_WORDS 2u
#define SELINOS_TCB_RESUME_M2_REPLY_WORDS 1u
#define SELINOS_TCB_RESUME_M2_REPLY_CAPS 1u
#define SELINOS_TCB_RESUME_M2_CHILD_COMPLETION_WORDS 3u

/* sel4utils reserves slots 0-7 in every configured process CSpace. */
#define SELINOS_TCB_RESUME_M2_TASKD_CLIENT_ENDPOINT_SLOT 8u
#define SELINOS_TCB_RESUME_M2_TASKD_OBJECT_ENDPOINT_SLOT 9u
#define SELINOS_TCB_RESUME_M2_TASKD_CHILD_COMPLETION_SLOT 10u
#define SELINOS_TCB_RESUME_M2_TASKD_SUCCESS_NOTIFY_SLOT 11u
#define SELINOS_TCB_RESUME_M2_TASKD_TCB_DEST_SLOT 12u
#define SELINOS_TCB_RESUME_M2_OBJECT_ENDPOINT_SLOT 8u
#define SELINOS_TCB_RESUME_M2_OBJECT_TCB_SOURCE_SLOT 9u
#define SELINOS_TCB_RESUME_M2_CHILD_COMPLETION_SEND_SLOT 8u
#define SELINOS_TCB_RESUME_M2_PROBE_CLIENT_ENDPOINT_SLOT 8u
#define SELINOS_TCB_RESUME_M2_PROBE_SUCCESS_NOTIFY_SLOT 9u

#endif
