// SPDX-License-Identifier: MIT
#ifndef SELINOS_TCB_LEASE_M1_PROTOCOL_H
#define SELINOS_TCB_LEASE_M1_PROTOCOL_H

#include <sel4/sel4.h>

/* Phase 32: transfer an inert preprovisioned child TCB cap without exercising it. */
#define SELINOS_TCB_LEASE_M1_REQUEST 0x54434d3152455154ull /* "TCM1REQT" */
#define SELINOS_TCB_LEASE_M1_GRANTED 0x54434d3147524e54ull /* "TCM1GRNT" */
#define SELINOS_TCB_LEASE_M1_SLOT 1u

#define SELINOS_TCB_LEASE_M1_REQUEST_WORDS 2u
#define SELINOS_TCB_LEASE_M1_REPLY_WORDS 1u
#define SELINOS_TCB_LEASE_M1_REPLY_CAPS 1u

/* sel4utils reserves slots 0-7 in every configured process CSpace. */
#define SELINOS_TCB_LEASE_M1_TASKD_CLIENT_ENDPOINT_SLOT 8u
#define SELINOS_TCB_LEASE_M1_TASKD_OBJECT_ENDPOINT_SLOT 9u
#define SELINOS_TCB_LEASE_M1_TASKD_SUCCESS_NOTIFY_SLOT 10u
#define SELINOS_TCB_LEASE_M1_TASKD_TCB_DEST_SLOT 11u
#define SELINOS_TCB_LEASE_M1_OBJECT_ENDPOINT_SLOT 8u
#define SELINOS_TCB_LEASE_M1_OBJECT_TCB_SOURCE_SLOT 9u
#define SELINOS_TCB_LEASE_M1_PROBE_CLIENT_ENDPOINT_SLOT 8u
#define SELINOS_TCB_LEASE_M1_PROBE_SUCCESS_NOTIFY_SLOT 9u

#endif
