// SPDX-License-Identifier: MIT
#ifndef SELINOS_TASKD_DYNAMIC_VSPACE_M0_PROTOCOL_H
#define SELINOS_TASKD_DYNAMIC_VSPACE_M0_PROTOCOL_H

#include <sel4/sel4.h>

/* Phase 53: one status-only witness after root-side PML4 rollback. */
#define SELINOS_TASKD_DYNAMIC_VSPACE_M0_REQUEST_WORDS 2u
#define SELINOS_TASKD_DYNAMIC_VSPACE_M0_REPLY_WORDS 3u
#define SELINOS_TASKD_DYNAMIC_VSPACE_M0_OWNERSHIP_QUERY 1u
#define SELINOS_TASKD_DYNAMIC_VSPACE_M0_PLAN_SLOT 1u
#define SELINOS_TASKD_DYNAMIC_VSPACE_M0_OWNED 0x80u
#define SELINOS_TASKD_DYNAMIC_VSPACE_M0_REJECTED 0x81u
#define SELINOS_TASKD_DYNAMIC_VSPACE_M0_ROLLBACK_GENERATION 1u
#define SELINOS_TASKD_DYNAMIC_VSPACE_M0_OWNED_GENERATION 2u

/* Slots 0–7 are reserved by sel4utils in configured process CSpaces. */
#define SELINOS_TASKD_DYNAMIC_VSPACE_M0_SERVER_ENDPOINT_SLOT 8u
#define SELINOS_TASKD_DYNAMIC_VSPACE_M0_OWNED_ROOT_SLOT 9u
#define SELINOS_TASKD_DYNAMIC_VSPACE_M0_PROBE_ENDPOINT_SLOT 8u
#define SELINOS_TASKD_DYNAMIC_VSPACE_M0_PROBE_SUCCESS_NOTIFY_SLOT 9u

#endif
