// SPDX-License-Identifier: MIT
#ifndef SELINOS_TASKD_M1_PROTOCOL_H
#define SELINOS_TASKD_M1_PROTOCOL_H

#include <sel4/sel4.h>

/* Phase 25 M1 is a private fixed-child lifecycle protocol, not Linux clone. */
#define SELINOS_TASKD_M1_START 0x544d315354415254ull /* "TM1START" */
#define SELINOS_TASKD_M1_CHILD_DONE 0x544d31444f4e4521ull /* "TM1DONE!" */
#define SELINOS_TASKD_M1_SUCCESS 0x544d314f4b212121ull /* "TM1OK!!!" */
#define SELINOS_TASKD_M1_CHILD_ID 1u
#define SELINOS_TASKD_M1_FIRST_GENERATION 1u
#define SELINOS_TASKD_M1_SECOND_GENERATION 2u

#define SELINOS_TASKD_M1_CLIENT_REQUEST_WORDS 2u
#define SELINOS_TASKD_M1_CHILD_COMPLETION_WORDS 3u
/* sel4utils reserves slots 0-7 in each configured process CSpace. */
#define SELINOS_TASKD_M1_CLIENT_ENDPOINT_SLOT 8u
#define SELINOS_TASKD_M1_CHILD_COMPLETION_SLOT 9u
#define SELINOS_TASKD_M1_CHILD_START_SLOT 10u
#define SELINOS_TASKD_M1_CHILD_TCB_SLOT 11u
#define SELINOS_TASKD_M1_PROBE_SUCCESS_SLOT 12u

#define SELINOS_TASKD_M1_CHILD_START_WAIT_SLOT 8u
#define SELINOS_TASKD_M1_CHILD_COMPLETION_SEND_SLOT 9u
#define SELINOS_TASKD_M1_PROBE_CLIENT_ENDPOINT_SLOT 8u
#define SELINOS_TASKD_M1_PROBE_SUCCESS_WAIT_SLOT 9u

#endif
