// SPDX-License-Identifier: MIT
#pragma once

#include <sel4/sel4.h>

#define SELINOS_TASKD_DYN_M0_REQUEST_WORDS 2u
#define SELINOS_TASKD_DYN_M0_REPLY_WORDS 3u
#define SELINOS_TASKD_DYN_M0_RESERVE 1u
#define SELINOS_TASKD_DYN_M0_RELEASE 2u
#define SELINOS_TASKD_DYN_M0_SLOT 1u
#define SELINOS_TASKD_DYN_M0_RESERVED 0x50u
#define SELINOS_TASKD_DYN_M0_EBUSY 0x51u
#define SELINOS_TASKD_DYN_M0_RELEASED 0x52u
#define SELINOS_TASKD_DYN_M0_SERVER_ENDPOINT_SLOT 8u
#define SELINOS_TASKD_DYN_M0_PROBE_ENDPOINT_SLOT 8u
#define SELINOS_TASKD_DYN_M0_PROBE_SUCCESS_NOTIFY_SLOT 9u
