// SPDX-License-Identifier: MIT
#ifndef SELINOS_TASKD_INERT_BUNDLE_M0_PROTOCOL_H
#define SELINOS_TASKD_INERT_BUNDLE_M0_PROTOCOL_H

#include <sel4/sel4.h>

/* Phase 54: status-only ownership witness after complete root-side rollback. */
#define SELINOS_TASKD_INERT_BUNDLE_M0_REQUEST_WORDS 2u
#define SELINOS_TASKD_INERT_BUNDLE_M0_REPLY_WORDS 3u
#define SELINOS_TASKD_INERT_BUNDLE_M0_OWNERSHIP_QUERY 1u
#define SELINOS_TASKD_INERT_BUNDLE_M0_PLAN_SLOT 1u
#define SELINOS_TASKD_INERT_BUNDLE_M0_OWNED 0x90u
#define SELINOS_TASKD_INERT_BUNDLE_M0_REJECTED 0x91u
#define SELINOS_TASKD_INERT_BUNDLE_M0_ROLLBACK_GENERATION 1u
#define SELINOS_TASKD_INERT_BUNDLE_M0_OWNED_GENERATION 2u
#define SELINOS_TASKD_INERT_BUNDLE_M0_CNODE_SLOT_BITS 4u

/* Slots 0–7 are reserved by sel4utils in configured process CSpaces. */
#define SELINOS_TASKD_INERT_BUNDLE_M0_SERVER_ENDPOINT_SLOT 8u
#define SELINOS_TASKD_INERT_BUNDLE_M0_TCB_SLOT 9u
#define SELINOS_TASKD_INERT_BUNDLE_M0_CNODE_SLOT 10u
#define SELINOS_TASKD_INERT_BUNDLE_M0_VSPACE_ROOT_SLOT 11u
#define SELINOS_TASKD_INERT_BUNDLE_M0_PROBE_ENDPOINT_SLOT 8u
#define SELINOS_TASKD_INERT_BUNDLE_M0_PROBE_SUCCESS_NOTIFY_SLOT 9u

#endif
