// SPDX-License-Identifier: MIT
#ifndef SELINOS_ROOT_DISPATCH_M0_PROTOCOL_H
#define SELINOS_ROOT_DISPATCH_M0_PROTOCOL_H

#include <sel4/sel4.h>

/* Phase 35 M0: root status dispatch only; no construction or cap delivery. */
#define SELINOS_ROOT_DISPATCH_M0_REQUEST 0x52444d3052455151ull /* "RDM0REQQ" */
#define SELINOS_ROOT_DISPATCH_M0_READY 0x52444d3052445930ull /* "RDM0RDY0" */
#define SELINOS_ROOT_DISPATCH_M0_SLOT 1u
#define SELINOS_ROOT_DISPATCH_M0_GENERATION 1u
#define SELINOS_ROOT_DISPATCH_M0_WORDS 3u
#define SELINOS_ROOT_DISPATCH_M0_PROBE_ENDPOINT_SLOT 8u

#endif
