// SPDX-License-Identifier: MIT
#ifndef SELINOS_TASKD_DYNAMIC_TCB_M0_PROTOCOL_H
#define SELINOS_TASKD_DYNAMIC_TCB_M0_PROTOCOL_H

#include <sel4/sel4.h>

/* Phase 51: query only whether taskd owns the dynamically moved inert target TCB cap. */
#define SELINOS_TASKD_DYNAMIC_TCB_M0_REQUEST_WORDS 2u
#define SELINOS_TASKD_DYNAMIC_TCB_M0_REPLY_WORDS 3u
#define SELINOS_TASKD_DYNAMIC_TCB_M0_OWNERSHIP_QUERY 1u
#define SELINOS_TASKD_DYNAMIC_TCB_M0_PLAN_SLOT 1u
#define SELINOS_TASKD_DYNAMIC_TCB_M0_OWNED 0x60u
#define SELINOS_TASKD_DYNAMIC_TCB_M0_REJECTED 0x61u

/* Slots 0–7 are reserved by sel4utils in configured process CSpaces. */
#define SELINOS_TASKD_DYNAMIC_TCB_M0_SERVER_ENDPOINT_SLOT 8u
#define SELINOS_TASKD_DYNAMIC_TCB_M0_TARGET_TCB_SLOT 9u
#define SELINOS_TASKD_DYNAMIC_TCB_M0_PROBE_ENDPOINT_SLOT 8u
#define SELINOS_TASKD_DYNAMIC_TCB_M0_PROBE_SUCCESS_NOTIFY_SLOT 9u

#endif
