// SPDX-License-Identifier: MIT
#ifndef SELINOS_TASKD_RESERVATION_M1_PROTOCOL_H
#define SELINOS_TASKD_RESERVATION_M1_PROTOCOL_H

#include <sel4/sel4.h>

/* Phase 30: coordinated status-only reservations, not capability leases. */
#define SELINOS_TASKD_RES_M1_RESERVE_BUNDLES 0x54524d3152535642ull /* "TRM1RSVB" */
#define SELINOS_TASKD_RES_M1_BOTH_RESERVED 0x54524d31424f5448ull /* "TRM1BOTH" */
#define SELINOS_TASKD_RES_M1_OBJECT_RESERVE 0x4f524d3152535653ull /* "ORM1RSVS" */
#define SELINOS_TASKD_RES_M1_OBJECT_RESERVED 0x4f524d3152454459ull /* "ORM1REDY" */
#define SELINOS_TASKD_RES_M1_MEM_RESERVE 0x4d524d3152535653ull /* "MRM1RSVS" */
#define SELINOS_TASKD_RES_M1_MEM_RESERVED 0x4d524d3152454459ull /* "MRM1REDY" */
#define SELINOS_TASKD_RES_M1_SLOT 1u

#define SELINOS_TASKD_RES_M1_REQUEST_WORDS 2u
#define SELINOS_TASKD_RES_M1_REPLY_WORDS 1u

/* sel4utils reserves slots 0-7 in each configured process CSpace. */
#define SELINOS_TASKD_RES_M1_CLIENT_ENDPOINT_SLOT 8u
#define SELINOS_TASKD_RES_M1_OBJECT_ENDPOINT_SLOT 9u
#define SELINOS_TASKD_RES_M1_MEM_ENDPOINT_SLOT 10u
#define SELINOS_TASKD_RES_M1_SUCCESS_NOTIFY_SLOT 11u
#define SELINOS_TASKD_RES_M1_OBJECT_SERVER_ENDPOINT_SLOT 8u
#define SELINOS_TASKD_RES_M1_MEM_SERVER_ENDPOINT_SLOT 8u
#define SELINOS_TASKD_RES_M1_PROBE_CLIENT_ENDPOINT_SLOT 8u
#define SELINOS_TASKD_RES_M1_PROBE_SUCCESS_NOTIFY_SLOT 9u

#endif
