// SPDX-License-Identifier: MIT
#ifndef SELINOS_OPAQUE_LEASE_M1_PROTOCOL_H
#define SELINOS_OPAQUE_LEASE_M1_PROTOCOL_H

#include <sel4/sel4.h>

/* Phase 31: one root-preprovisioned notification token, not a resource lease. */
#define SELINOS_OPAQUE_LEASE_M1_REQUEST 0x4f4c4d3152455154ull /* "OLM1REQT" */
#define SELINOS_OPAQUE_LEASE_M1_GRANTED 0x4f4c4d3147524e54ull /* "OLM1GRNT" */
#define SELINOS_OPAQUE_LEASE_M1_SLOT 1u

#define SELINOS_OPAQUE_LEASE_M1_REQUEST_WORDS 2u
#define SELINOS_OPAQUE_LEASE_M1_REPLY_WORDS 1u
#define SELINOS_OPAQUE_LEASE_M1_REPLY_CAPS 1u

/* sel4utils reserves slots 0-7 in each configured process CSpace. */
#define SELINOS_OPAQUE_LEASE_M1_TASKD_CLIENT_ENDPOINT_SLOT 8u
#define SELINOS_OPAQUE_LEASE_M1_TASKD_OBJECT_ENDPOINT_SLOT 9u
#define SELINOS_OPAQUE_LEASE_M1_TASKD_SUCCESS_NOTIFY_SLOT 10u
#define SELINOS_OPAQUE_LEASE_M1_TASKD_TOKEN_DEST_SLOT 11u
#define SELINOS_OPAQUE_LEASE_M1_OBJECT_ENDPOINT_SLOT 8u
#define SELINOS_OPAQUE_LEASE_M1_OBJECT_TOKEN_SOURCE_SLOT 9u
#define SELINOS_OPAQUE_LEASE_M1_PROBE_CLIENT_ENDPOINT_SLOT 8u
#define SELINOS_OPAQUE_LEASE_M1_PROBE_SUCCESS_NOTIFY_SLOT 9u

#endif
