// SPDX-License-Identifier: MIT
#ifndef SELINOS_TASKD_POPULATED_CSPACE_M0_PROTOCOL_H
#define SELINOS_TASKD_POPULATED_CSPACE_M0_PROTOCOL_H

#include <sel4/sel4.h>

/* Phase 56: one status witness for a configured but non-running one-cap CSpace. */
#define SELINOS_TASKD_POPULATED_CSPACE_M0_REQUEST_WORDS 2u
#define SELINOS_TASKD_POPULATED_CSPACE_M0_REPLY_WORDS 3u
#define SELINOS_TASKD_POPULATED_CSPACE_M0_OWNERSHIP_QUERY 1u
#define SELINOS_TASKD_POPULATED_CSPACE_M0_PLAN_SLOT 1u
#define SELINOS_TASKD_POPULATED_CSPACE_M0_OWNED 0xb0u
#define SELINOS_TASKD_POPULATED_CSPACE_M0_REJECTED 0xb1u
#define SELINOS_TASKD_POPULATED_CSPACE_M0_ROLLBACK_GENERATION 1u
#define SELINOS_TASKD_POPULATED_CSPACE_M0_OWNED_GENERATION 2u
#define SELINOS_TASKD_POPULATED_CSPACE_M0_CNODE_SLOT_BITS 4u
#define SELINOS_TASKD_POPULATED_CSPACE_M0_TARGET_NOTIFICATION_SLOT 1u

/* Slots 0–7 are reserved by sel4utils in configured process CSpaces. */
#define SELINOS_TASKD_POPULATED_CSPACE_M0_SERVER_ENDPOINT_SLOT 8u
#define SELINOS_TASKD_POPULATED_CSPACE_M0_TCB_SLOT 9u
#define SELINOS_TASKD_POPULATED_CSPACE_M0_CNODE_SLOT 10u
#define SELINOS_TASKD_POPULATED_CSPACE_M0_VSPACE_ROOT_SLOT 11u
#define SELINOS_TASKD_POPULATED_CSPACE_M0_PROBE_ENDPOINT_SLOT 8u
#define SELINOS_TASKD_POPULATED_CSPACE_M0_PROBE_SUCCESS_NOTIFY_SLOT 9u

#endif
