#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Generate the bounded immutable newc CPIO fixture embedded by selinos-romfsd."""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "src/projects/helixos/servers/romfs_archive.c"
FILES = (
    ("/selinos-release", b"SELINOS!"),
    ("/selinos-banner", b"CPIO-OK!"),
    ("/selinos-version", b"SELINOS9"),
)


def align4(data: bytearray) -> None:
    data.extend(b"\0" * ((-len(data)) & 3))


def header(ino: int, mode: int, size: int, namesize: int) -> bytes:
    fields = (
        ino,
        mode,
        0,
        0,
        1,
        0,
        size,
        0,
        0,
        0,
        0,
        namesize,
        0,
    )
    encoded = b"070701" + b"".join(f"{field:08x}".encode("ascii") for field in fields)
    if len(encoded) != 110:
        raise RuntimeError("newc header size mismatch")
    return encoded


def append_member(archive: bytearray, ino: int, name: str, data: bytes, mode: int = 0o100644) -> None:
    name_bytes = name.encode("ascii") + b"\0"
    align4(archive)
    archive.extend(header(ino, mode, len(data), len(name_bytes)))
    archive.extend(name_bytes)
    align4(archive)
    archive.extend(data)


def c_source(archive: bytes) -> str:
    rows = []
    for offset in range(0, len(archive), 12):
        row = ", ".join(f"0x{byte:02x}u" for byte in archive[offset:offset + 12])
        rows.append(f"    {row},")
    return """// SPDX-License-Identifier: MIT
/* Generated by tools/generate_romfs_cpio_fixture.py; do not edit by hand. */
#include <stddef.h>

#include \"selinos_romfs_archive.h\"

const unsigned char selinos_romfs_cpio_archive[] = {
%s
};

const size_t selinos_romfs_cpio_archive_size = sizeof(selinos_romfs_cpio_archive);
""" % "\n".join(rows)


def main() -> int:
    archive = bytearray()
    for ino, (name, data) in enumerate(FILES, start=1):
        append_member(archive, ino, name, data)
    append_member(archive, len(FILES) + 1, "TRAILER!!!", b"", mode=0)
    align4(archive)
    OUTPUT.write_text(c_source(bytes(archive)), encoding="utf-8")
    print(f"generated {OUTPUT} ({len(archive)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
